# Change these first
owner: materialsproject # Your GitHub organization or username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Materials Project Public
    url: https://materialsproject.org
  - name: Materials Project Development
    url: https://next-gen.materialsproject.org
  - name: Materials Project API
    url: https://api.materialsproject.org
  - name: Materials Project Authentication
    url: https://profile.materialsproject.org
  - name: MPContribs
    url: https://contribs.materialsproject.org
  - name: Legacy Materials Project Website
    url: https://legacy.materialsproject.org
#   - name: Test for HEAD
#     method: HEAD
#     url: https://www.google.com
#   - name: Secret Site
#     url: $SECRET_SITE
#   - name: TCP ping
#     url: 1.1.1.1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.materialsproject.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status
  logoUrl: https://next-gen.materialsproject.org/assets/images/home/materials-project-logo.svg
  name: Materials Project
  introTitle: "**Materials Project** is an open-access database of predicted materials properties."
  introMessage: This status page reports the uptime for the services we provide and tracks any on-going incidents. If you have been redirected to this page when trying to visit materialsproject.org, it is likely because there is an ongoing incident or planned maintenance.
  navbar:
    - title: Status
      href: /
    - title: Materials Project
      href: https://materialsproject.org

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
